name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  jest-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Run Unit Tests (Jest)
        run: npm test

  cypress-tests:
    runs-on: ubuntu-latest
    needs: jest-tests

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Build Application
        run: npm run build

      - name: Start Application
        run: |
          npm start &
        env:
          NODE_ENV: test

      - name: Wait for Application to be Ready
        run: npx wait-on http://localhost:4200

      - name: Run Cypress Tests
        run: npx cypress run --headless

  deploy:
    runs-on: ubuntu-latest
    needs:
      - jest-tests
      - cypress-tests
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Dependencies
        run: npm install

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npm install -g vercel
          vercel deploy --prod --confirm --token $VERCEL_TOKEN
